felixedel/flirror

flirror/__init__.py
flirror/crawler/__init__.py
flirror/crawler/crawlers.py
flirror/crawler/main.py
flirror/database.py
flirror/exceptions.py
flirror/google_auth.py
flirror/templates/weather.html
flirror/utils.py
flirror/views.py
setup.py

This was nice for the start, but shouldn't be done this way. Thus,
all external APIs can now be scraped with the flirror-crawler command
line tool and store there results in a sqlite database. The flirror
webserver retrieves the data to show from this database.

Move crawling of external APIs out of Flask application

---

.gitignore
flirror/crawler/crawlers.py
flirror/crawler/google_auth.py
flirror/database.py
flirror/templates/weather.html
flirror/views.py

When displaying the data on the smartmirror, we are interesting in the
current data set. Storing only the current data set in DB and always
overwrite this with a new one, makes retrieving the data in the view
simpler and doesn't require a cleanup mechanism after a certain time.
Changes:
e71501c (Felix Schmidt, 6 minutes ago)
Add the long missing .gitignore file
c81f184 (Felix Schmidt, 7 minutes ago)
Use FlirrorObject to store and retrieve calendar information
db3479a (Felix Schmidt, 3 weeks ago)
Use FlirrorObject to store and retrieve weather information
462c569 (Felix Schmidt, 3 weeks ago)
Use store_object_by_key method to store arbitrary FlirrorObjects
fd9d679 (Felix Schmidt, 3 weeks ago)
Use FlirrorObject class for Google OAuth

Use single data objects per crawler to only store the current data

---

flirror/crawler/crawlers.py
flirror/crawler/google_auth.py

Changes:
12acbe2 (Felix Schmidt, 9 minutes ago)
Fix wrong return value of refresh_access_token
In comparison to the other authentication functions, this one returned the
full token_data dictionary rather than only the access token.
Using this code path fails the Google authentication, as the whole 
dictionary cannot be converted to unicode.
100594b (Felix Schmidt, 30 minutes ago)
Store initial refresh token with every new access token
It looks like only the initial access token provides a refresh token. All
access tokens that are requested by using this refresh token, don't provide
an own refresh token. As we are always overwriting the old access token
with the new one, we must keep the old refresh token if the new access
token does not provide one by itself.

Fix wrong handling of access and fresh tokens in some cases

---

flirror/crawler/__init__.py

This way, the configuration of the "flirror" logger also takes effect on
packages which are on the same level like the crawler package because
they are used for both, the crawler and the webserver(e.g. the database
package), but still provide useful log output for the crawler
application.

Initialize application's root logger as "flirror" in crawler package

---

.gitignore
flirror/__init__.py
flirror/crawler/crawlers.py
flirror/crawler/google_auth.py
flirror/crawler/main.py
flirror/database.py
flirror/exceptions.py
flirror/views.py
settings.example.cfg
tests/conftest.py
tests/test_google_auth.py
tests/testdata/client_secret.json
tox.ini

Changes:
41a414a (Felix Schmidt, 73 seconds ago)
Fix test_get_oauth_flow_missing test to work with a clean environment
20960da (Felix Schmidt, 33 minutes ago)
Add tests for remaining GoogleOAuth methods
eafbcb1 (Felix Schmidt, 7 days ago)
Let pytest-coverage report missing lines in terminal
84dd99d (Felix Schmidt, 7 days ago)
Use dedicated database instances for testing
Although the connection was configurable before, it couldn't be used 
effectively for testing as the object behind the database was still the 
same and thus could not simply be teared down and set up again for each 
test. Therefore, this change explicitly creates dedicated Database
instances, so there is no magic "db" object that is used in the background
for every transaction. The drawback of this is, that the database …

Configure pytest, add tests for Google authentication and improve handling of database connection

---

flirror/crawler/crawlers.py
setup.py

For humanizing dates in the UI we are already using arrow. To not rely
on multiple "dateutil" packages, we could remove python-dateutil and
switch to arrow.

Remove python-dateutil and use arrow instead

---

flirror/crawler/main.py
tests/crawler/test_scheduling.py

Changes:
aaa7985 (Felix Schmidt, 3 minutes ago)
Fix pytest warning "cannot collect test class 'TestCrawler'"
PytestCollectionWarning: cannot collect test class 'TestCrawler' because it
has a __init__ constructor (from:
tests/crawler/test_scheduling.py)
class TestCrawler(Crawler):
0949970 (Felix Schmidt, 7 minutes ago)
Make periodic option configurable
eea7b8e (Felix Schmidt, 24 minutes ago)
Allow crawling of single modules
Specify a single (or multiple) modules via the -m option.

Allow direct crawling of single modules and make peridic crawling configurable

---

flirror/api.py
flirror/crawler/crawlers.py
flirror/templates/error.html
flirror/templates/module.html
flirror/views.py
settings.example.cfg

Changes:
0245e03 (Felix Schmidt, 21 seconds ago)
Update settings example file
17efa99 (Felix Schmidt, 11 minutes ago)
Provide module_id parameter to API endpoints in index view
fca5ee5 (Felix Schmidt, 36 minutes ago)
Recreate error template (which got accidentially deleted)
e2cff60 (Felix Schmidt, 36 minutes ago)
Fix error handling in index view
df878e9 (Felix Schmidt, 45 minutes ago)
Provide module_id to API endpoints via GET parameter
This way, each API endpoint can be used for multiple tiles of the same 
type.
821ccab (Felix Schmidt, 62 minutes ago)
Use module id as key for storing data from crawlers

Allow using the same module multiple times with different configuration

---

flirror/crawler/main.py
flirror/static/css/style.css
flirror/templates/index.html
flirror/templates/modules/stocks.html
flirror/views.py
settings.example.cfg

Changes:
c382059 (Felix Schmidt, 58 seconds ago)
Make display time of carousel items configurable
979f580 (Felix Schmidt, 30 hours ago)
Align height of tiles
This should ensure that the cards always have the same height as the row,
thus all tiles should have the same height.
d0f304b (Felix Schmidt, 31 hours ago)
Show multiple modules in a single position as bootstrap carousel
3539ac1 (Felix Schmidt, 2 days ago)
Group and sort modules by position in index view
... to allow combination of multiple modules in a single tile
15d1db5 (Felix Schmidt, 2 days ago)
Improve structure of configuration file
This change changes the module config to a list rather than dicts as they
are simpler to sort. Additionally, it introduces sections in the that
should help to keep a better overview and allow …

Allow multiple modules per position via bootstrap carousel

---

.gitignore
flirror/__init__.py
flirror/static/all.css
flirror/static/scss/all.scss
flirror/templates/layout.html
flirror/templates/modules/clock.html
flirror/views.py
setup.py

c8e2c5a (Felix Schmidt, 7 minutes ago)
Use moment.js to format date/time in clock module
d7df157 (Felix Schmidt, 7 days ago)
Add webassets-cache directory to gitignore file
40d760f (Felix Schmidt, 7 days ago)
Make analog clock really round
Due to bootstrap's border-box property, the indicators of the clock weren't
positioned equally and the clock itself wasn't 100 percent round.
c4a46b0 (Felix Schmidt, 8 days ago)
Implement digital clock
85d947f (Felix Schmidt, 8 days ago)
Show date above clock
eac395b (Felix Schmidt, 11 days ago)
Add clock module (pure CSS with a little JavaScript)
I found this at https://codepen.io/kylewetton/pen/QJbOjw and adapted a few
lines to fit the page layout.
8e992ef (Felix Schmidt, 11 days ago)
Load javascript files at the top of the page
Otherwise, we won't be …

Implement clock module (analog and digital) with JavaScript and CSS

---

flirror/__init__.py
flirror/api.py
flirror/templates/ajax.html
flirror/templates/index.html
flirror/templates/layout.html
flirror/templates/module.html
flirror/templates/modules/calendar.html
flirror/templates/modules/clock.html
flirror/templates/modules/newsfeed.html
flirror/templates/modules/stocks.html
flirror/templates/modules/weather.html
flirror/utils.py
flirror/views.py

To make the Jinja2 templates reusable also within the Ajax calls, this
introduces a new "output" parameter for the module API that allows
returning the result in raw format or as template. The first one is
still used to initially fill the index view during page load. The
template is used by the ajax calls to simply replace the HTML within
the module divs.
b18c448 (Felix Schmidt, 3 weeks ago)
Enable ajax reloading for all modules
Except for the clock, as this is a pure JS/CSS module which doesn't need
any backend data.
501ef95 (Felix Schmidt, 3 weeks ago)
Refactor current API endpoints to support raw and template output
41915c5 (Felix Schmidt, 3 weeks ago)
Use output parameter for API to differentiate between raw and template
87b78c7 (Felix Schmidt, 4 weeks ago)
Fix wrong year formatting …

Implement ajax reloading for all modules

---

flirror/crawler/crawlers.py

When making the flirror crawlers more robust, I was too optimistic about
the exception field being always present in the newsfeed library.

Fix bozo_exception attribute error

---

.travis.yml
tox.ini

So far, this was set to 3.6 because 3.7 was not available in Travis CI.

Update Python version to 3.7 in tox and Travis CI config

---

CHANGELOG.md
dockerfiles/flirror-Dockerfile

We keep the "build from sources" to allow automated builds on docker hub
to build a new image whenever a change is merged to master (latest) or a
tag is pushed (concrete release).

Use flirror-Dockerfile for automated builds on docker hub

---

CHANGELOG.md
README.md
deploy/docker-compose.example.yaml
settings.example.cfg

The docker-compose.example.yaml file uses the image uploaded to docker
hub instead of the local flirror-Dockerfile.

Provide a docker-compose example file for flirror deployment

---

CHANGELOG.md
README.md
flirror/__init__.py
flirror/crawler/main.py
flirror/modules/clock/__init__.py
flirror/templates/ajax.html
flirror/templates/index.html
flirror/views.py
settings.example.cfg

This makes it more clear that one should specify the module's name here
and not some mysterious type.
To avoid having the name modules on different hierarchy levels in the
data structure, I renamed the "modules" list used in the template
context to "tiles" (which is what they are in the end - from a visual
point of view).

Rename config key modules.type to modules.module

---

flirror/crawler/main.py
flirror/modules/calendar/__init__.py
flirror/modules/newsfeed/__init__.py
flirror/modules/stocks/__init__.py
flirror/modules/weather/__init__.py

This unifies the parameters between view and crawler, so we always have
module_* variables in both places. This should also clearify the module
API for custom plugins a little bit.

Rename crawler_id to module_id

---

dockerfiles/flirror-Dockerfile

Since we are using a multi-stage Docker image now, this dependency must
be installed as runtime dependency in the final stage. Otherwise we are
not able to load the needed python classes from Pillow (in our case
qrcode which uses Pillow).

Keep libjpeg as runtime dependency in flirror-Dockerfile

---

docker-compose.yaml

With this change we can use the prebuilt flirror-css image from docker
hub for our Travis CI builds. To test the current development version
we mount the local workspace into the /src directory of the container.
This should speed up the Travis CI builds for the CSS tests as we don't
have to build the Docker image with every build.

Prepuild the flirror-css image and upload it to Docker hub

---

flirror/modules/weather/__init__.py
flirror/utils.py
poetry.lock
pyproject.toml
tox.ini

Looks like this got missing when switching to Poetry. The config is
already there, so we just need to add the package and fix some wrong
ordered imports.

Add flake8-import-order and fix flake8 config

---

.travis.yml

I just noticed these warnings when looking into the build results on
travis-ci.com. I don't do that often since the GitHub checks results are
sufficient for most use cases.
Looks like some keys got deprecated in the meantime or where missing the
whole time.
- root: deprecated key sudo (The key `sudo` has no effect anymore.)
- root: missing dist, using the default xenial
- root: missing os, using the default linux

Fix travis CI warnings and switch to bionic
